package com.mycompany.hosted.checkoutFlow.exceptions;

public enum EndpointRuntimeReason {
	
	CREATE_EXECUTE_IO,
	CREATE_FAILED_HTTP_STATUS,
	CREATE_MISSING_ID,
	CREATE_RESPONSE_NULL,
	CREATE_NULL_SESSION_ATTRS,
	CREATE_MISSING_LOGINTYPE,
	DETAILS_EXECUTE_IO,
	DETAILS_FAILED_HTTP_STATUS,
	DETAILS_NULL_SERVER_ID,
	DETAILS_COMPARE_SCRIPT_SERVER,
	DETAILS_COMPARE_PARAMETERS,
	DETAILS_NULL_CUSTOMER,
	DETAILS_FIELDS_EMPTY,
	DETAILS_NULL_CARD,
	CAPTURE_VALIDATE_DETAILS,
	CAPTURE_EXECUTE_IO,
	CAPTURE_FAILED_HTTP_STATUS,
	CAPTURE_FIELDS_EMPTY,
	CAPTURE_EMPTY_CAPTURE_ID,
	CAPTURE_NULL_PROCESSOR_RESPONSE,
	//CAPTURE_FAILED_NO_REASON,
	REFUND_ORDER_NOT_RETRIEVABLE,
	REFUND_ERROR_DETAIL_NOT_FOUND,
	REFUND_NULL_ORDER_IN_ERROR_DETAIL,
	REFUND_EXECUTE_IOEXCEPTION,
	REFUND_FAILED_HTTP_STATUS,
	REFUND_ID_MISSING,
	NULL_ATTRIBUTE

}
